// export.js - 会话导出功能

import { state } from './state.js';
import * as api from './api.js';
import { showToast } from './toast.js';
import { t } from './i18n.js';

/**
 * 将树形结构转换为Markdown格式
 * @param {Object} session - 会话数据
 * @returns {string}
 */
function convertToMarkdown(session) {
  const lines = [];
  lines.push(`# ${session.name}`);
  lines.push('');
  lines.push(`> 创建时间: ${new Date(session.startTime).toLocaleString()}`);
  lines.push('');
  
  function buildMarkdown(node, depth = 0) {
    const indent = '  '.repeat(depth);
    const title = node.title || '无标题';
    const url = node.url;
    const visitInfo = node.visitCount > 1 ? ` (访问${node.visitCount}次)` : '';
    
    lines.push(`${indent}- [${title}](${url})${visitInfo}`);
    
    if (node.children && node.children.length > 0) {
      for (const childId of node.children) {
        const child = session.allNodes[childId];
        if (child) {
          buildMarkdown(child, depth + 1);
        }
      }
    }
  }
  
  for (const rootId of session.rootNodes) {
    const root = session.allNodes[rootId];
    if (root) {
      buildMarkdown(root);
    }
  }
  
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by MindGit*');
  
  return lines.join('\n');
}

/**
 * 将树形结构转换为JSON格式
 * @param {Object} session - 会话数据
 * @returns {string}
 */
function convertToJSON(session) {
  const exportData = {
    name: session.name,
    createdAt: new Date(session.startTime).toISOString(),
    exportTime: new Date().toISOString(),
    nodes: []
  };
  
  function buildJSON(node) {
    const result = {
      title: node.title,
      url: node.url,
      visitCount: node.visitCount || 1,
      timestamp: node.timestamp,
      children: []
    };
    
    if (node.children && node.children.length > 0) {
      for (const childId of node.children) {
        const child = session.allNodes[childId];
        if (child) {
          result.children.push(buildJSON(child));
        }
      }
    }
    
    return result;
  }
  
  for (const rootId of session.rootNodes) {
    const root = session.allNodes[rootId];
    if (root) {
      exportData.nodes.push(buildJSON(root));
    }
  }
  
  return JSON.stringify(exportData, null, 2);
}

/**
 * 将树形结构转换为HTML格式
 * @param {Object} session - 会话数据
 * @returns {string}
 */
function convertToHTML(session) {
  const lines = [];
  lines.push('<!DOCTYPE html>');
  lines.push('<html lang="zh-CN">');
  lines.push('<head>');
  lines.push(`<meta charset="UTF-8">`);
  lines.push(`<title>${escapeHtml(session.name)} - MindGit 导出</title>`);
  lines.push('<style>');
  lines.push(`
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; background: #f5f7fa; }
    h1 { color: #2c3e50; border-bottom: 2px solid #4a90d9; padding-bottom: 10px; }
    .meta { color: #7f8c8d; font-size: 14px; margin: 20px 0; }
    ul { list-style: none; padding-left: 20px; }
    li { margin: 8px 0; }
    a { color: #4a90d9; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .visit-count { color: #7f8c8d; font-size: 12px; }
    .depth-0 { font-weight: 600; }
    .depth-1 { margin-left: 20px; }
    .depth-2 { margin-left: 40px; }
    .depth-3 { margin-left: 60px; }
    footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #95a5a6; font-size: 12px; }
  `);
  lines.push('</style>');
  lines.push('</head>');
  lines.push('<body>');
  lines.push(`<h1>${escapeHtml(session.name)}</h1>`);
  lines.push(`<div class="meta">创建时间: ${new Date(session.startTime).toLocaleString()}</div>`);
  lines.push('<ul>');
  
  function buildHTML(node, depth = 0) {
    const title = escapeHtml(node.title || '无标题');
    const url = escapeHtml(node.url);
    const visitInfo = node.visitCount > 1 ? ` <span class="visit-count">(访问${node.visitCount}次)</span>` : '';
    
    lines.push(`<li class="depth-${Math.min(depth, 3)}"><a href="${url}" target="_blank">${title}</a>${visitInfo}</li>`);
    
    if (node.children && node.children.length > 0) {
      lines.push('<ul>');
      for (const childId of node.children) {
        const child = session.allNodes[childId];
        if (child) {
          buildHTML(child, depth + 1);
        }
      }
      lines.push('</ul>');
    }
  }
  
  for (const rootId of session.rootNodes) {
    const root = session.allNodes[rootId];
    if (root) {
      buildHTML(root);
    }
  }
  
  lines.push('</ul>');
  lines.push('<footer>Generated by MindGit</footer>');
  lines.push('</body>');
  lines.push('</html>');
  
  return lines.join('\n');
}

/**
 * HTML 转义
 */
function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * 下载文件
 * @param {string} content - 文件内容
 * @param {string} filename - 文件名
 * @param {string} mimeType - MIME 类型
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * 创建导出格式选择对话框
 * @returns {Promise<string|null>} 选择的格式或 null
 */
function showExportFormatDialog() {
  return new Promise((resolve) => {
    // 移除已存在的对话框
    const existing = document.getElementById('exportFormatModal');
    if (existing) existing.remove();
    
    const modal = document.createElement('div');
    modal.id = 'exportFormatModal';
    modal.className = 'modal active';
    modal.innerHTML = `
      <div class="modal-content" style="max-width: 320px;">
        <div class="modal-header">
          <h2>📤 选择导出格式</h2>
          <button class="close-btn" id="closeExportFormat">&times;</button>
        </div>
        <div class="modal-body">
          <div class="export-options" style="display: flex; flex-direction: column; gap: 10px;">
            <button class="export-option-btn" data-format="markdown" style="padding: 14px; border: 1.5px solid var(--border-color); border-radius: 10px; background: var(--card-bg); cursor: pointer; text-align: left; transition: all 0.2s;">
              <div style="font-weight: 600; color: var(--text-primary); margin-bottom: 4px;">📝 Markdown</div>
              <div style="font-size: 12px; color: var(--text-muted);">纯文本格式，适合导入到笔记软件</div>
            </button>
            <button class="export-option-btn" data-format="html" style="padding: 14px; border: 1.5px solid var(--border-color); border-radius: 10px; background: var(--card-bg); cursor: pointer; text-align: left; transition: all 0.2s;">
              <div style="font-weight: 600; color: var(--text-primary); margin-bottom: 4px;">🌐 HTML</div>
              <div style="font-size: 12px; color: var(--text-muted);完整网页，可用浏览器打开查看</div>
            </button>
          </div>
        </div>
      </div>
    `;
    
    document.body.appendChild(modal);
    
    // 关闭按钮
    modal.querySelector('#closeExportFormat').addEventListener('click', () => {
      modal.remove();
      resolve(null);
    });
    
    // 点击背景关闭
    modal.addEventListener('click', (e) => {
      if (e.target === modal) {
        modal.remove();
        resolve(null);
      }
    });
    
    // ESC 关闭
    const handleEsc = (e) => {
      if (e.key === 'Escape') {
        modal.remove();
        resolve(null);
        document.removeEventListener('keydown', handleEsc);
      }
    };
    document.addEventListener('keydown', handleEsc);
    
    // 格式选择
    modal.querySelectorAll('.export-option-btn').forEach(btn => {
      btn.addEventListener('mouseenter', () => {
        btn.style.borderColor = 'var(--primary-color)';
        btn.style.background = 'var(--hover-bg)';
      });
      btn.addEventListener('mouseleave', () => {
        btn.style.borderColor = 'var(--border-color)';
        btn.style.background = 'var(--card-bg)';
      });
      btn.addEventListener('click', () => {
        const format = btn.dataset.format;
        modal.remove();
        document.removeEventListener('keydown', handleEsc);
        resolve(format);
      });
    });
  });
}

/**
 * 导出当前会话
 */
export async function exportCurrentSession() {
  if (!state.currentSessionId) {
    showToast('请先选择一个会话');
    return;
  }
  
  const result = await api.getSessionTree(state.currentSessionId);
  if (!result.session) {
    showToast('会话不存在');
    return;
  }
  
  const session = result.session;
  
  // 显示格式选择对话框
  const format = await showExportFormatDialog();
  if (!format) return;
  
  const timestamp = new Date().toISOString().slice(0, 10);
  const baseFilename = `${session.name.replace(/[^\w\u4e00-\u9fa5]/g, '_')}_${timestamp}`;
  
  if (format === 'markdown') {
    const content = convertToMarkdown(session);
    downloadFile(content, `${baseFilename}.md`, 'text/markdown');
    showToast('已导出为 Markdown');
  } else if (format === 'html') {
    const content = convertToHTML(session);
    downloadFile(content, `${baseFilename}.html`, 'text/html');
    showToast('已导出为 HTML');
  }
}

/**
 * 导出所有会话
 */
export async function exportAllSessions() {
  const result = await api.getSessions();
  const sessions = result.sessions;
  
  if (!sessions || Object.keys(sessions).length === 0) {
    showToast('没有可导出的会话');
    return;
  }
  
  const exportData = {
    exportTime: new Date().toISOString(),
    totalSessions: Object.keys(sessions).length,
    sessions: sessions
  };
  
  const content = JSON.stringify(exportData, null, 2);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(content, `mindgit_all_sessions_${timestamp}.json`, 'application/json');
  showToast('已导出所有会话');
}
